In [ ]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

import io
df2 = pd.read_csv(io.BytesIO(uploaded['sequences.csv']))
df2

difference.to_csv('difference.csv')
from google.colab import files
files.download("difference.csv")

In [ ]:
from math import sqrt
difference = pd.DataFrame(columns=['data'])
for i in range(13):
  for j in range(i,13):
    difference = difference.append({'data' :sqrt((numbers['sepal_length'][i] - numbers['sepal_length'][j])**2 +
         (numbers['sepal_width'][i] - numbers['sepal_width'][j])**2 +
         (numbers['petal_length'][i] - numbers['petal_length'][j])**2 +
         (numbers['petal_width'][i] - numbers['petal_width'][j])**2
         ), 'index': f'{i+1} - {j+1}'},ignore_index= True)

# difference = difference.append({'data' :sqrt((numbers['sepal_length'][0] - numbers['sepal_length'][1])**2 +
#          (numbers['sepal_width'][0] - numbers['sepal_width'][1])**2 +
#          (numbers['petal_length'][0] - numbers['petal_length'][1])**2 +
#          (numbers['petal_width'][0] - numbers['petal_width'][1])**2
#          )},ignore_index= True)
print(difference)

In [ ]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],[10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_
# array([1, 1, 1, 0, 0, 0], dtype=int32)
kmeans.predict([[0, 0], [12, 3]])
# array([1, 0], dtype=int32)
kmeans.cluster_centers_
# array([[10.,  2.],
#        [ 1.,  2.]]) 

# fit(X[, y, sample_weight])              |   Compute k-means clustering.

# fit_predict(X[, y, sample_weight])      |   Compute cluster centers and predict cluster index for each sample.

# fit_transform(X[, y, sample_weight])    |   Compute clustering and transform X to cluster-distance space.

# get_params([deep])                      |   Get parameters for this estimator.

# predict(X[, sample_weight])             |   Predict the closest cluster each sample in X belongs to.

# score(X[, y, sample_weight])            |   Opposite of the value of X on the K-means objective.

# set_params(**params)                    |   Set the parameters of this estimator.

# transform(X)                            |   Transform X to a cluster-distance space.

array([[10.,  2.],
       [ 1.,  2.]])

## PLOT


In [ ]:
import matplotlib.pyplot as plt

# Distance entre ADN

In [ ]:

import io
df2 = pd.read_csv(io.BytesIO(uploaded['sequences.csv']))
df2

In [1]:
from pprint import pprint
def LevenshteinDistance( s:str, t:str):
  m = len(s)
  n = len(t)
  # // for all i and j, d[i,j] will hold the Levenshtein distance between
  # // the first i characters of s and the first j characters of t
  # declare int d[0..m, 0..n]

  d = [[] for i in range(m+1)]
  for i in range(m+1):
    d[i] = [0 for j in range(n+1)]
 
  for i in range(m+1):
    d[i][0] = i
  for i in range(n+1):
    d[0][i] = i

  outputSum = 0
  for i in range(1,m+1):
    for j in range(1,n+1):
      cost = 0 if s[i-1] == t[j-1] else 1
      d[i][j]= min([
                    d[i-1][j] + 1,
                    d[i][j-1] + 1,
                    d[i-1][j-1] + cost,
      ])
  pprint(d)
  return d[m][n]

In [ ]:
# from pprint import pprint
d = LevenshteinDistance("CTAC","CTAG")
# min([sum(x) for x in d])
d

[[0, 1, 2, 3, 4],
 [1, 0, 0, 0, 0],
 [2, 0, 0, 0, 0],
 [3, 0, 0, 0, 0],
 [4, 0, 0, 0, 0]]
[[0, 1, 2, 3, 4],
 [1, 0, 1, 2, 3],
 [2, 1, 0, 1, 2],
 [3, 2, 1, 0, 1],
 [4, 3, 2, 1, 1]]


1

In [ ]:
from google.colab import files
import pandas as pd
import io

uploaded = files.upload()

Saving dna_data.csv to dna_data (1).csv


In [ ]:
df2 = pd.read_csv(io.BytesIO(uploaded['dna_data.csv']))


In [ ]:
df2

sequences
0  CCAGCTGCATCACAGGAGGCCAGCGAGCAGGTCTGTTCCAAGGGCC...
1  AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCC...
2  GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...
3  GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...
4  GCTCAGCCCCCAGGTCACCCAGGAACTGACGTGAGTGTCCCCATCC...
5  CAGACTGGGTGGACAACAAAACCTTCAGCGGTAAGAGAGGGCCAAG...

In [ ]:
def calc_distance(s1:str, s2:str):
  n=len(s1)
  dis=0
  for i in range(n):
      if s1[i]!=s2[i]:
        dis+=1
  return dis        
calc_distance('AAT','AAC')

1

In [ ]:
# df=df2
# df2['distance'] = df2.apply(lambda row: calc_distance(row['sequences'], row['sequences']), axis=1)# sequence
# df2.drop(df2.columns[1], axis=1, inplace=True)

list_seq=df2.values.tolist() #convert the datafrarme to a list

m,n = len(list_seq),len(list_seq)  #number of rows and columns of the matrix is equal to the number of the sequences

d = [[] for i in range(m)]
for i in range(m):
  d[i] = [0 for j in range(n)]

# this one is for the calc of the matrix of distances between each pair of sequences
i=0
j=0
for seq_1 in list_seq:
  if i==6:
    i=0
  for seq_2 in list_seq:
    if j==6:
      j=0
    d[i][j]=calc_distance(seq_1[0],seq_2[0])
    j+=1
  i+=1
print(d)

# this one to calculate the sum of each row and put it in a dictionary
dic={}
ind=0
for line in d:
  print(sum(line))
  dic[ind]=sum(line)
  ind+=1

#this function is to calculate the minimum value in the dictionary
def minimums(some_dict):
    positions = [] # output variable
    min_value = float("inf")
    for k, v in some_dict.items():
        if v == min_value:
            positions.append(k)
        if v < min_value:
            min_value = v
            positions = [] # output variable
            positions.append(k)

    return positions

min=minimums(dic)
print(f'The central sequence is the sequence {min[0]} "{list_seq[min[0]][0]}"')

[[0, 38, 41, 44, 44, 47], [38, 0, 48, 39, 41, 38], [41, 48, 0, 43, 41, 45], [44, 39, 43, 0, 42, 41], [44, 41, 41, 42, 0, 49], [47, 38, 45, 41, 49, 0]]
214
204
218
209
217
220
The central sequence is the sequence 1 "AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCCCTCCGTGCCCCCGC"


# K-means and K-medoid

In [ ]:
# prepare the dependencies
import matplotlib.pyplot as plt
# from kneed import KneeLocator
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

ModuleNotFoundError: ignored

In [ ]:
# upload the data
from google.colab import files
uploaded = files.upload()

Saving iris_minime.csv to iris_minime.csv


In [ ]:
# set the data in pandas and display it
import io
import pandas as pd

df2 = pd.read_csv(io.BytesIO(uploaded['iris_minime.csv']))
df2

sepallength  sepalwidth  petallength  petalwidth
0          5.10         3.5         1.40        0.20
1          4.96         3.0         1.40        0.20
2          7.00         3.2         4.70        1.40
3          4.70         3.2         3.20        0.20
4          6.70         3.0         5.20        2.30
5          6.40         3.2         1.48        1.50
6          5.00         3.6         1.40        0.20
7          5.40         3.9         1.70        0.40
8          6.90         4.8         4.90        1.50
9          6.70         3.3         5.40        2.50
10         6.30         3.1         5.00        1.90
11         4.60         3.1         1.50        0.24
12         6.50         3.0         5.20        2.00

In [ ]:
from sklearn.cluster import KMeans
kmeans = KMeans(
    init="random",
    n_clusters=3,
    n_init=1,
    max_iter=10
)
sign = kmeans.fit(df2)

In [ ]:
sign

KMeans(algorithm='auto', copy_x=True, init='random', max_iter=10, n_clusters=3,
       n_init=1, n_jobs=None, precompute_distances='auto', random_state=None,
       tol=0.0001, verbose=0)

In [ ]:
kmeans.cluster_centers_

array([[5.16571429, 3.35714286, 1.72571429, 0.42      ],
       [6.95      , 4.        , 4.8       , 1.45      ],
       [6.55      , 3.1       , 5.2       , 2.175     ]])

In [ ]:
kmeans.labels_

array([0, 0, 1, 0, 2, 0, 0, 0, 1, 2, 2, 0, 2], dtype=int32)

## K-medoid

## Import DNA Dataset

In [ ]:
# upload the data
from google.colab import files
uploaded = files.upload()

Saving dna_data.csv to dna_data.csv


In [ ]:
import io
import pandas as pd

dna_dataset = pd.read_csv(io.BytesIO(uploaded['dna_data.csv']))

In [ ]:
type(dna_dataset)

pandas.core.frame.DataFrame

In [ ]:
def numerize(row):
  sequence = row['sequences']
  output = []
  i = 0
  for i in range(len(sequence)):
    ascii_value = ord(sequence[i])
    output.append(ascii_value)
  return output
numeric_dna_dataset = dna_dataset.copy(True)
numeric_dna_dataset['numeric_sequence'] = dna_dataset.apply(numerize, axis=1)

In [ ]:
numeric_dna_dataset

# K medoid Implementation

In [ ]:
# import the dependencies
import pandas as pd
from pandas.core.frame import DataFrame as Df

In [ ]:
class KMedoids():
  # n_clusters: number of clusters
  # 
  def __init__(self, n_clusters, distance_function, data_cols, n_iterations = 5, initial_points = 'random'):
    # set the number of clusters to process
    self.n_clusters = n_clusters
    # specify the distance function between each two elements
    self.distance_function = distance_function
    # specify the list of column(s) that are relevant to the Kmedoids PAM
    self.cols = data_cols
    # set the initial centroids of the clusters or they're set as random
    self.initial_points = initial_points
    # set the number of iterations that the Kmedoid will repeat
    self.n_iterations = n_iterations

  
  @property
  def n_iterations(self):
    return self._n_iterations
  
  @n_iterations.setter
  def n_iterations (self, value:int):
    if value < 0:
      raise Exception("Number of iterations is negtive and needs to be positive")
    self._n_iterations = value

  @property
  def cols(self):
    return self._cols
  
  @cols.setter
  def cols(self, value):
    if type(value) is list:
      self._cols = value
    else:
      if type(value) is str:
        self._cols = [value]
      else:
        raise Exception("the specified column(s) is neither a list nor a str")
    self.dimension = len(value)

  @property
  def n_clusters(self):
    return self._n_clusters
  
  @n_clusters.setter
  def n_clusters(self, value):
    self._n_clusters = value
  
  @property
  def distance_function(self):
    return self._distance_function
  
  @distance_function.setter
  def distance_function(self, value):
    if  not callable(value):
      raise Exception("Distance function variable is not a function")
    if value.__code__.co_argcount != 2:
      raise Exception("Distance function doesn't have the right shape")
    self._distance_function = value
  
  @property
  def iterations(self):
    
    return self._iterations
  
  @iterations.setter
  def iterations(self, value:list):
    self._iterations = value
  
  def _assign_centroid(self,data:Df):
    
    def sanitize(row):
      return int(row['assigned_centroid'][len('dist_from_center_'):])
    
    output =  data.copy(True)
    # get the rows that contain the distances only
    distance_columns = data.filter(regex='^dist_from_center_')
    
    # assign each point to its closes centroid
    output['assigned_centroid'] = distance_columns.idxmin(axis = 1)

    # sanitize the centroid mention by removing the unnecessary prefix
    output['assigned_centroid'] = output.apply(sanitize,axis=1)
    
    return output
  
  def _compute_distances(self, data:Df, centroids:Df):
    output = data.copy(True)
    for index, centroid in centroids.iterrows():
      dist_colname = f'dist_from_center_{index}'
      output[dist_colname] = output.apply(lambda x: self.distance_function(centroid,x), axis=1)
    
    return output
  

  def _get_clusters(self, data:Df, centroids:Df):
    clusters= []
    for index,centroid in centroids.iterrows():
      clusters.append(data[data.assigned_centroid == index])
    
    return clusters
  
  def _compute_cost(self, clusters):
    sum = 0
    for clust in clusters:
      for index,row in clust.iterrows():
        sum+=row[f'dist_from_center_{row["assigned_centroid"]}']
    return sum
  
  # def _is_better(self, iterations):
  #   if not hasattr(self,'_first'):
  #     self._first = True
  #     return True
  #   else:
  #     return False
  
    

  def _select_centroid(self, data:Df, centroids):
    added_centroid = data.sample(1)
    centroids = centroids.sample(centroids.count()[0] - 1)
    
    return pd.merge(added_centroid, centroids, how= 'outer')
      
  def fit(self, data: Df):
    # we copy the data into another data frame that we process
    processing_df = data.copy(True)

    # we initialize the inital centroids randomly (or selected)
    if self.initial_points == 'random':
      # print("here")
      self.centroids = processing_df.sample(self.n_clusters)
    else:
      # TODO: implement manual centroid selection
      raise NotImplementedError()
    
    self.iterations = [{
        'centroids': self.centroids
    }]
    curr_itr = 0
    swap_cost = 1
    # while self._is_better(self.iterations[curr_itr]):
    while swap_cost > 0 :
      current_iteration = self.iterations[curr_itr]
      # processing_df = data.copy(True)
      # we select the non-centroid data from the dataset
      current_iteration['non_centroids'] = processing_df[~processing_df.index.isin(current_iteration['centroids'].index)]

      # we calculate the distance from the self.centroids to each point 
      current_iteration['non_centroids'] = self._compute_distances(current_iteration['non_centroids'], current_iteration['centroids'])
      
      # assign each point to a centroid
      current_iteration['non_centroids'] = self._assign_centroid(current_iteration['non_centroids'])
      
      # we get the individual clusters from the dataset
      current_iteration['clusters'] =  self._get_clusters(current_iteration['non_centroids'], current_iteration['centroids'])

      # we compute the cost
      current_iteration['cost'] = self._compute_cost(current_iteration['clusters'])
      
      new_centroids = self._select_centroid(current_iteration['non_centroids'], current_iteration['centroids'])

      # return new_centroids

      if curr_itr > 0:
        swap_cost = self.iterations[curr_itr]['cost'] - self.iterations[curr_itr - 1]['cost'] 

      if swap_cost > 0:
        curr_itr+= 1
        self.iterations.append({
            'centroids': new_centroids
        })
    return processing_df


In [ ]:
def dna_distance(left, right):
  s1 = left.sequences
  s2 = right.sequences
  n= len(s2) if len(s1) > len(s2) else len(s1)
  dis=0
  for i in range(n):
      if s1[i]!=s2[i]:
        dis+=1
  return dis
# dna_distance.__code__.co_argcount
kmd = KMedoids(2,dna_distance,'sequences')

In [ ]:
output = kmd.fit(dna_dataset)

count is Empty DataFrame
Columns: [sequences]
Index: []
count is                                            sequences  ...  assigned_centroid
0  GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...  ...                NaN

[1 rows x 4 columns]


In [ ]:
kmd.iterations[1]['non_centroids']

sequences  ...  assigned_centroid
2  GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...  ...                  1
3  GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...  ...                  1
4  GCTCAGCCCCCAGGTCACCCAGGAACTGACGTGAGTGTCCCCATCC...  ...                  0
5  CAGACTGGGTGGACAACAAAACCTTCAGCGGTAAGAGAGGGCCAAG...  ...                  0

[4 rows x 4 columns]

In [ ]:
dna_distance(dna_dataset.iloc[3],dna_dataset.iloc[1])

39

In [ ]:
kmd.centroids

AttributeError: ignored

In [ ]:
output[~output.index.isin(kmd.iterations[0]['centroids'].index)]
# kmd.iterations[0]['centroids'].index

sequences  ...  assigned_centroid
0  CCAGCTGCATCACAGGAGGCCAGCGAGCAGGTCTGTTCCAAGGGCC...  ...                  4
1  AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCC...  ...                  5
2  GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...  ...                  4
3  GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...  ...                  5

[4 rows x 4 columns]

In [ ]:
centers = kmd.iterations[0]['centroids']

sequences
5  CAGACTGGGTGGACAACAAAACCTTCAGCGGTAAGAGAGGGCCAAG...

In [ ]:
# pd.merge(centers.sample(centers.count()[0] -1), output.sample(), how='outer')
centers.sample(centers.count()[0] -1)
# output

sequences
5  CAGACTGGGTGGACAACAAAACCTTCAGCGGTAAGAGAGGGCCAAG...

In [ ]:
kmd.iterations[0]['centroids']['sequences'][3]

'GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTTGCTCGGTTTTCCCC'

## The Easy Way

In [ ]:
!pip install biopython
import Bio.Cluster as kcluster
from Bio.Cluster import kmedoids 
import numpy as np

     |████████████████████████████████| 2.3MB 7.4MB/s 


In [ ]:
distance = np.array([[1,2,3],[4,5,6],[3,5,7]])
clusterid, error, found = kmedoids(distance)


In [ ]:
print((clusterid, error, found))

(array([0, 1, 0], dtype=int32), 3.0, 1)


In [ ]:
from pprint import pprint
def LevenshteinDistance( s:str, t:str):
  m = len(s)
  n = len(t)
  # // for all i and j, d[i,j] will hold the Levenshtein distance between
  # // the first i characters of s and the first j characters of t
  # declare int d[0..m, 0..n]

  d = [[] for i in range(m+1)]
  for i in range(m+1):
    d[i] = [0 for j in range(n+1)]
 
  for i in range(m+1):
    d[i][0] = i
  for i in range(n+1):
    d[0][i] = i

  outputSum = 0
  for i in range(1,m+1):
    for j in range(1,n+1):
      cost = 0 if s[i-1] == t[j-1] else 1
      d[i][j]= min([
                    d[i-1][j] + 1,
                    d[i][j-1] + 1,
                    d[i-1][j-1] + cost,
      ])
  # pprint(d)
  return d[m][n]

In [ ]:
d = LevenshteinDistance("CTAC","CTAG")

In [ ]:
# prepping the data
import pandas as pd

dna_data = list(dna_dataset['sequences'])
# dna_data = .pivot(columns='sequences',values='val')
dist_matrix = [[ LevenshteinDistance(dna,dna2) for dna2 in dna_data] for dna in dna_data]
dist_matrix

[[0, 31, 33, 33, 30, 32],
 [31, 0, 37, 33, 29, 31],
 [33, 37, 0, 36, 34, 33],
 [33, 33, 36, 0, 33, 30],
 [30, 29, 34, 33, 0, 35],
 [32, 31, 33, 30, 35, 0]]

In [ ]:


distance = np.array(dist_matrix)
result = kmedoids(distance)
# clusterid, error, found = result
print(result)

(array([4, 4, 5, 5, 4, 5], dtype=int32), 122.0, 1)


# Agnes
Agglomerative Nesting
(single-linkage dissimilarity formula used in class)

In [ ]:
# compute distance matrix
# prepping the data
import pandas as pd

dna_data = list(dna_dataset['sequences'])
# dna_data = .pivot(columns='sequences',values='val')
dist_matrix = [[ LevenshteinDistance(dna,dna2) for dna2 in dna_data] for dna in dna_data]
dist_matrix

[[0, 31, 33, 33, 30, 32],
 [31, 0, 37, 33, 29, 31],
 [33, 37, 0, 36, 34, 33],
 [33, 33, 36, 0, 33, 30],
 [30, 29, 34, 33, 0, 35],
 [32, 31, 33, 30, 35, 0]]

In [ ]:
from sklearn.cluster import AgglomerativeClustering as agnes

agns = agnes(n_clusters=4, affinity='precomputed', linkage='single')

agns_result = agns.fit_predict(dist_matrix)


In [ ]:
dna_dataset['cluster_id'] = agns_result
dna_dataset

sequences  cluster_id
0  CCAGCTGCATCACAGGAGGCCAGCGAGCAGGTCTGTTCCAAGGGCC...           0
1  AGACCCGCCGGGAGGCGGAGGACCTGCAGGGTGAGCCCCACCGCCC...           0
2  GAGGTGAAGGACGTCCTTCCCCAGGAGCCGGTGAGAAGCGCAGTCG...           3
3  GGGCTGCGTTGCTGGTCACATTCCTGGCAGGTATGGGGCGGGGCTT...           1
4  GCTCAGCCCCCAGGTCACCCAGGAACTGACGTGAGTGTCCCCATCC...           0
5  CAGACTGGGTGGACAACAAAACCTTCAGCGGTAAGAGAGGGCCAAG...           2

#Additional Work

##Importing dna dataset

In [43]:
!gdown --id 18dW-BGxv8HkaXDGcoZixcrWEUZ-MrUrJ
!echo "n1,n2,sequence" > dna_examples.csv
!tail -n +7 dna_examples_.txt >> dna_examples.csv

Downloading...
From: https://drive.google.com/uc?id=18dW-BGxv8HkaXDGcoZixcrWEUZ-MrUrJ
To: /content/dna_examples_.txt
100% 36.7k/36.7k [00:00<00:00, 14.3MB/s]


In [44]:
import pandas as pd

dna_dataset = pd.read_csv('dna_examples.csv')

In [45]:
dna_dataset

n1  ...                                           sequence
0    EI  ...               CAGACTGGGTGGACAACAAAACCTTCAGCGGTA...
1    EI  ...               CCTTTGAGGACAGCACCAAGAAGTGTGCAGGTA...
2    EI  ...              CCCTCGTGCGGTCCACGACCAAGACCAGCGGTGA...
3    EI  ...              TGGCGACTACGGCGCGGAGGCCCTGGAGAGGTGA...
4    EI  ...              AAGCTGACAGTGGACCCGGTCAACTTCAAGGTGA...
..   ..  ...                                                ...
355  EI  ...              CTGGTGTGCTCTCTGGTGATCAAGATACAGGTAG...
356  EI  ...              AACCAACTGTTACAATCAAGGTCTATGAAGGTAA...
357  EI  ...              GGCTTCCCGTGCAACCAGTTTGGGCATCAGGTGC...
358  EI  ...                GGTGCCTCAGCGTTCGGGCTGGAGACGAGGGT...
359  EI  ...                AGGACAGAGGAGGCGCGTCCGGCCTTCCTGGT...

[360 rows x 3 columns]

In [ ]:
dna_data = pd.DataFrame(index=dna_dataset['sequence'], columns=dna_dataset['sequence'])

In [ ]:
dna_data

CAGACTGGGTGGACAACAAAACCTTCAGCGGTAAGAGAGGGCCAAGCTCAGAGACCACAG  ...               AGGACAGAGGAGGCGCGTCCGGCCTTCCTGGTGAGCGTGTCTGCCCTCCCTGCGTCAGGA
sequence                                                                                                                      ...                                                                           
             CAGACTGGGTGGACAACAAAACCTTCAGCGGTAA...                                               <NA>                         ...                                               <NA>                        
             CCTTTGAGGACAGCACCAAGAAGTGTGCAGGTAC...                                               <NA>                         ...                                               <NA>                        
            CCCTCGTGCGGTCCACGACCAAGACCAGCGGTGAG...                                               <NA>                         ...                                               <NA>                        
            TGGCGACTACGGCGCGGAGGCCCTGGAGAGGTGAG...                                               <NA>                         ...                                               <NA>                        
            AAGCTGACAGTGGACCCGGTCAACTTCAAGGTGAG...                                               <NA>                         ...                                               <NA>                        
...                                                                                               ...                         ...                                                ...                        
            CTGGTGTGCTCTCTGGTGATCAAGATACAGGTAGG...                                               <NA>                         ...                                               <NA>                        
            AACCAACTGTTACAATCAAGGTCTATGAAGGTAAT...                                               <NA>                         ...                                               <NA>                        
            GGCTTCCCGTGCAACCAGTTTGGGCATCAGGTGCG...                                               <NA>                         ...                                               <NA>                        
              GGTGCCTCAGCGTTCGGGCTGGAGACGAGGGTG...                                               <NA>                         ...                                               <NA>                        
              AGGACAGAGGAGGCGCGTCCGGCCTTCCTGGTG...                                               <NA>                         ...                                               <NA>                        

[360 rows x 348 columns]

## Data Prep

In [46]:
!pip install biopython
import Bio.Cluster as kcluster
from Bio.Cluster import kmedoids 
import numpy as np
import pandas as pd

     |████████████████████████████████| 2.3MB 4.1MB/s 


In [3]:
def LevenshteinDistance( s:str, t:str):
  m = len(s)
  n = len(t)
  # // for all i and j, d[i,j] will hold the Levenshtein distance between
  # // the first i characters of s and the first j characters of t
  # declare int d[0..m, 0..n]

  d = [[] for i in range(m+1)]
  for i in range(m+1):
    d[i] = [0 for j in range(n+1)]
 
  for i in range(m+1):
    d[i][0] = i
  for i in range(n+1):
    d[0][i] = i

  outputSum = 0
  for i in range(1,m+1):
    for j in range(1,n+1):
      cost = 0 if s[i-1] == t[j-1] else 1
      d[i][j]= min([
                    d[i-1][j] + 1,
                    d[i][j-1] + 1,
                    d[i-1][j-1] + cost,
      ])
  pprint(d)
  return d[m][n]

In [10]:
!pip install python-Levenshtein


     |████████████████████████████████| 50 kB 340 kB/s eta 0:00:01
  Created wheel for python-Levenshtein: filename=python_Levenshtein-0.12.2-cp39-cp39-linux_x86_64.whl size=80156 sha256=3bfa9654ca739b7b9babaecf460e01398e104c74738e0667f3be706003a4752d
  Stored in directory: /home/jovyan/.cache/pip/wheels/46/4a/6c/164a1d9dd67c82d208f19d869ad0a517a0c5a6117f608c53e6
Successfully built python-Levenshtein


In [8]:
from random import randint
def generate_dna(length: int):
        ADN = ''
        for i in range(0,length):
            ADN+='ACGT'[randint(0,3)]
        return ADN
first, second = generate_dna(10),generate_dna(10)
print(first,second)


CATAAGCCCG CACAAATCCC


In [16]:
import Levenshtein
Levenshtein.distance(first,second)

4

In [ ]:
for rowIndex, row in dna_data.to_pandas().iterrows(): #iterate over rows
    for columnIndex, value in row.items():
        dna_data.at[rowIndex, columnIndex] = LevenshteinDistance(rowIndex, columnIndex)

In [ ]:
# save data
dna_data.to_csv("computed_distances.csv")
from google.colab import files
files.download("computed_distances.csv")

In [48]:
# retreive data
from google.colab import files
import io
uploaded = files.upload()
dna_data = pd.read_csv(io.BytesIO(uploaded['computed_distances.csv']))

Saving computed_distances.csv to computed_distances.csv


In [49]:
dna_data

sequence  ...                AGGACAGAGGAGGCGCGTCCGGCCTTCCTGGTGAGCGTGTCTGCCCTCCCTGCGTCAGGA
0                 CAGACTGGGTGGACAACAAAACCTTCAGCGGTA...  ...                                                 33                         
1                 CCTTTGAGGACAGCACCAAGAAGTGTGCAGGTA...  ...                                                 33                         
2                CCCTCGTGCGGTCCACGACCAAGACCAGCGGTGA...  ...                                                 36                         
3                TGGCGACTACGGCGCGGAGGCCCTGGAGAGGTGA...  ...                                                 29                         
4                AAGCTGACAGTGGACCCGGTCAACTTCAAGGTGA...  ...                                                 29                         
..                                                 ...  ...                                                ...                         
355              CTGGTGTGCTCTCTGGTGATCAAGATACAGGTAG...  ...                                                 38                         
356              AACCAACTGTTACAATCAAGGTCTATGAAGGTAA...  ...                                                 41                         
357              GGCTTCCCGTGCAACCAGTTTGGGCATCAGGTGC...  ...                                                 35                         
358                GGTGCCTCAGCGTTCGGGCTGGAGACGAGGGT...  ...                                                 31                         
359                AGGACAGAGGAGGCGCGTCCGGCCTTCCTGGT...  ...                                                  0                         

[360 rows x 361 columns]

In [51]:
dna_numpy_data = np.empty((360,360))
for i in range(dna_data.values.shape[0]):
  dna_numpy_data[i] = np.delete(dna_data.values[i],0)
dna_numpy_data

array([[ 0., 33., 29., ..., 36., 37., 33.],
       [33.,  0., 30., ..., 34., 35., 33.],
       [29., 30.,  0., ..., 28., 37., 36.],
       ...,
       [36., 34., 28., ...,  0., 39., 35.],
       [37., 35., 37., ..., 39.,  0., 31.],
       [33., 33., 36., ..., 35., 31.,  0.]])

##PAM Clustering

In [ ]:
labels, error, found = kmedoids(dna_numpy_data, nclusters=2)
(labels, error, found)

In [54]:
print(f"our cluster centroids are the dna strings number: {set(labels)}")

our cluster centroids are the dna strings number: {201, 38}


###silhouette Testing

In [ ]:
# testing the initial number of clusters using the sihlouette
from sklearn import metrics

metrics.silhouette_score(dna_numpy_data, labels, metric="precomputed")

0.013935802121169598

In [ ]:
k_range = (2,11)

silhouettes = {}
for i in range(*k_range):
  labels , error, found = kmedoids(dna_numpy_data, nclusters=i)
  silhouette_coef = metrics.silhouette_score(dna_numpy_data, labels, metric="precomputed")
  silhouettes[silhouette_coef] = i

print(silhouettes)

{0.012004897727229305: 2, 0.008969087647055477: 3, 0.009248467596836165: 4, 0.007372918129872044: 5, 0.009019678564239039: 6, 0.018053766026673548: 7, 0.018755777882912748: 8, 0.012765767249068439: 9, 0.021322538673705843: 10}


In [ ]:
best_k = silhouettes[max(silhouettes.keys())]
best_k

10

##Agnes Clustering

In [ ]:
from sklearn.cluster import AgglomerativeClustering as agnes

agns = agnes(n_clusters=10, affinity='precomputed', linkage='average')

agns_result = agns.fit_predict(dna_numpy_data)

In [ ]:
agns_result

In [ ]:
unique, counts = np.unique(agns_result, return_counts=True)
dict(zip(unique, counts))

{0: 166, 1: 11, 2: 6, 3: 6, 4: 79, 5: 23, 6: 57, 7: 1, 8: 10, 9: 1}

##Silhouette Example

In [ ]:
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn import datasets
X, y = datasets.load_iris(return_X_y=True)

In [ ]:
import numpy as np
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=3, random_state=1).fit(X)
labels = kmeans_model.labels_
metrics.silhouette_score(X, labels, metric='euclidean')

##Iris dataset

In [ ]:
!gdown --id 1HyXhm_gBbwI0JMB-ZCWFMOfuez5LVt16
!echo "sepallength,sepalwidth,petallength,petalwidth,class" > iris_dataset.csv
!tail -n +73 iris_test.txt >> iris_dataset.csv
!sed -i '/6.1,3.0,? ,4.9,1.8,Iris-virginica/c\6.1,3.0,4.9,1.8,Iris-virginica' iris_dataset.csv

Downloading...
From: https://drive.google.com/uc?id=1HyXhm_gBbwI0JMB-ZCWFMOfuez5LVt16
To: /content/iris_test.txt
100% 7.70k/7.70k [00:00<00:00, 13.6MB/s]


In [ ]:
!cat iris_dataset.csv

wc: 129: No such file or directory


In [ ]:
import numpy as np
import pandas as pd
  
iris_dataset = pd.read_csv('iris_dataset.csv')

In [ ]:
# replacing ? by standard Nan
iris_dataset = iris_dataset.replace(to_replace="?", value=np.nan)

In [ ]:
# fix data types in columns

iris_columns = ['sepallength',	'sepalwidth',	'petallength',	'petalwidth']
for col in iris_columns:

  iris_dataset[col] = pd.to_numeric(iris_dataset[col], downcast="float")
# iris_dataset["sepalwidth"] = pd.to_numeric(iris_dataset["sepalwidth"], downcast="float")
# iris_dataset["petallength"] = pd.to_numeric(iris_dataset["petallength"], downcast="float")
# iris_dataset["petalwidth"] = pd.to_numeric(iris_dataset["petalwidth"], downcast="float")

In [ ]:
iris_dataset

sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          NaN         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
iris_dataset.groupby('class').mean()

sepallength  sepalwidth  petallength  petalwidth
class                                                            
Iris-setosa         5.006000    3.418000       1.4640    0.244000
Iris-versicolor     5.936000    2.772917       4.2600    1.328571
Iris-virginica      6.593617    2.974000       6.5625    4.150000

In [ ]:
for col in iris_columns:
  iris_dataset[col] = iris_dataset.groupby("class").transform(lambda x: x.fillna(x.mean()))

In [ ]:
iris_dataset

sepallength  sepalwidth  petallength  petalwidth           class
0       5.100000    5.100000     5.100000    5.100000     Iris-setosa
1       4.900000    4.900000     4.900000    4.900000     Iris-setosa
2       4.700000    4.700000     4.700000    4.700000     Iris-setosa
3       4.600000    4.600000     4.600000    4.600000     Iris-setosa
4       5.000000    5.000000     5.000000    5.000000     Iris-setosa
..           ...         ...          ...         ...             ...
145     6.700000    6.700000     6.700000    6.700000  Iris-virginica
146     6.300000    6.300000     6.300000    6.300000  Iris-virginica
147     6.500000    6.500000     6.500000    6.500000  Iris-virginica
148     6.200000    6.200000     6.200000    6.200000  Iris-virginica
149     6.593616    6.593616     6.593616    6.593616  Iris-virginica

[150 rows x 5 columns]

In [ ]:
iris_dataset.drop("class",axis=1).to_numpy()

###PAM Clustering

In [ ]:
!pip install scikit-learn-extra
from sklearn_extra.cluster import KMedoids

iris_numpy = iris_dataset.drop("class",axis=1).to_numpy()

kmedoids = KMedoids(n_clusters=3, method="pam").fit(iris_dataset.drop("class",axis=1))

In [ ]:
kmedoids.labels_, kmedoids.cluster_centers_

(array([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 2, 0, 1, 0, 1, 1, 2, 2, 2, 2, 0,
        2, 2, 0, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
        2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 1, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]),
 array([[6.5999999 , 6.5999999 , 6.5999999 , 6.5999999 , 0.        ],
        [5.        , 5.        , 5.        , 5.        , 1.        ],
        [5.69999981, 5.69999981, 5.69999981, 5.69999981, 2.        ]]))

In [ ]:
iris_dataset['clustering_results'] = kmedoids.labels_

In [ ]:
iris_dataset[iris_dataset.clustering_results == 2]

###AGNES

In [ ]:
from sklearn.cluster import AgglomerativeClustering as agnes

agns = agnes(n_clusters=3, affinity='euclidean', linkage='single')

agns_result = agns.fit_predict(iris_numpy)

In [ ]:
agns_result

array([2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 0, 1, 0, 2, 0, 2, 2, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 2, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
iris_dataset['agnes_result'] = agns_result

In [ ]:
iris_dataset

sepallength  sepalwidth  ...  clustering_results  agnes_result
0       5.100000    5.100000  ...                   1             2
1       4.900000    4.900000  ...                   1             2
2       4.700000    4.700000  ...                   1             2
3       4.600000    4.600000  ...                   1             2
4       5.000000    5.000000  ...                   1             2
..           ...         ...  ...                 ...           ...
145     6.700000    6.700000  ...                   0             0
146     6.300000    6.300000  ...                   0             0
147     6.500000    6.500000  ...                   0             0
148     6.200000    6.200000  ...                   0             0
149     6.593616    6.593616  ...                   0             0

[150 rows x 7 columns]

In [ ]:
# retreive data
from google.colab import files
import io
import pandas as pd
uploaded = files.upload()
iris_dataset = pd.read_csv(io.BytesIO(uploaded['iris_dataset.csv']))

##Setup Nvidia Acceleration

In [ ]:
!git clone https://github.com/rapidsai/rapidsai-csp-utils.git
!bash rapidsai-csp-utils/colab/rapids-colab.sh stable

Cloning into 'rapidsai-csp-utils'...
remote: Enumerating objects: 272, done.
remote: Counting objects: 100% (101/101), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 272 (delta 56), reused 38 (delta 19), pack-reused 171
Receiving objects: 100% (272/272), 79.66 KiB | 7.96 MiB/s, done.
Resolving deltas: 100% (118/118), done.
PLEASE READ FOR 21.06
********************************************************************************************************
Another release, another script change.  We had to revise the script, which now:
1. Does a more comprehensive install
2. Includes BlazingSQL
3. is far easier for everyone to understand and maintain

The script will require you to add these 5 cells to your notebook.  We have also created a new startup template: 
https://colab.research.google.com/drive/1TAAi_szMfWqRfHVfjGSqnGVLr_ztzUM9?usp=sharing

CHANGES T
CELL 1:
    # This get the RAPIDS-Colab install files and test check your GPU.  Run cells 1 and 2 only.
    # Please

In [ ]:
!nvidia-smi

Sat Jun 19 22:03:27 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.27       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# This get the RAPIDS-Colab install files and test check your GPU.  Run this and the next cell only.
# Please read the output of this cell.  If your Colab Instance is not RAPIDS compatible, it will warn you and give you remediation steps.
!python rapidsai-csp-utils/colab/env-check.py

***********************************************************************
Woo! Your instance has the right kind of GPU, a Tesla T4!
***********************************************************************



In [ ]:
!bash rapidsai-csp-utils/colab/update_gcc.sh
import os
os._exit(00)

Updating your Colab environment.  This will restart your kernel.  Don't Panic!
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Ign:3 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [697 B]
Hit:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Hit:9 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:10 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Ign:11 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages
Get:11 https://developer.download.nvidia.com/c

In [ ]:
# This will install CondaColab.  This will restart your kernel one last time.  Run this cell by itself and only run the next cell once you see the session crash.
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/latest/download/Mambaforge-colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:34
🔁 Restarting kernel...


In [ ]:
# Installing RAPIDS is now 'python rapidsai-csp-utils/colab/install_rapids.py <release> <packages>'
# The <release> options are 'stable' and 'nightly'.  Leaving it blank or adding any other words will default to stable.
# The <packages> option are default blank or 'core'.  By default, we install RAPIDSAI and BlazingSQL.  The 'core' option will install only RAPIDSAI and not include BlazingSQL, 
!python rapidsai-csp-utils/colab/install_rapids.py stable

Installing RAPIDS Stable 21.06
Starting the RAPIDS+BlazingSQL install on Colab.  This will take about 15 minutes.
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - cudatoolkit=11.0
    - gcsfs
    - llvmlite
    - openssl
    - python=3.7
    - rapids-blazing=21.06


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    abseil-cpp-20210324.1      |       h9c3ff4c_0        1015 KB  conda-forge
    aiohttp-3.7.4.post0        |   py37h5e8e339_0         625 KB  conda-forge
    anyio-3.2.0                |   py37h89c1867_0         138 KB  conda-forge
    appdirs-1.4.4              |     pyh9f0ad1d_0      